"""connection table

Revision ID: 191544c4cf40
Revises: 3614d6f8e889
Create Date: 2021-07-04 18:38:13.553005

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '191544c4cf40'
down_revision = '3614d6f8e889'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('connection', sa.Column('dateVisisted', sa.Date(), nullable=True))
    op.add_column('connection', sa.Column('country', sa.String(length=50), nullable=True))
    op.add_column('connection', sa.Column('city', sa.String(length=75), nullable=True))
    op.add_column('connection', sa.Column('lat', sa.Float(), nullable=True))
    op.add_column('connection', sa.Column('lon', sa.Float(), nullable=True))
    op.add_column('connection', sa.Column('isp', sa.String(length=50), nullable=True))
    op.add_column('connection', sa.Column('mobile', sa.Boolean(), nullable=True))
    op.add_column('connection', sa.Column('proxy', sa.Boolean(), nullable=True))
    op.drop_index('ix_connection_dateVisited', table_name='connection')
    op.create_index(op.f('ix_connection_city'), 'connection', ['city'], unique=False)
    op.create_index(op.f('ix_connection_country'), 'connection', ['country'], unique=False)
    op.create_index(op.f('ix_connection_dateVisisted'), 'connection', ['dateVisisted'], unique=False)
    op.create_index(op.f('ix_connection_isp'), 'connection', ['isp'], unique=False)
    op.create_index(op.f('ix_connection_lat'), 'connection', ['lat'], unique=False)
    op.create_index(op.f('ix_connection_lon'), 'connection', ['lon'], unique=False)
    op.create_index(op.f('ix_connection_mobile'), 'connection', ['mobile'], unique=False)
    op.create_index(op.f('ix_connection_proxy'), 'connection', ['proxy'], unique=False)
    op.drop_column('connection', 'dateVisited')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('connection', sa.Column('dateVisited', sa.DATE(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_connection_proxy'), table_name='connection')
    op.drop_index(op.f('ix_connection_mobile'), table_name='connection')
    op.drop_index(op.f('ix_connection_lon'), table_name='connection')
    op.drop_index(op.f('ix_connection_lat'), table_name='connection')
    op.drop_index(op.f('ix_connection_isp'), table_name='connection')
    op.drop_index(op.f('ix_connection_dateVisisted'), table_name='connection')
    op.drop_index(op.f('ix_connection_country'), table_name='connection')
    op.drop_index(op.f('ix_connection_city'), table_name='connection')
    op.create_index('ix_connection_dateVisited', 'connection', ['dateVisited'], unique=False)
    op.drop_column('connection', 'proxy')
    op.drop_column('connection', 'mobile')
    op.drop_column('connection', 'isp')
    op.drop_column('connection', 'lon')
    op.drop_column('connection', 'lat')
    op.drop_column('connection', 'city')
    op.drop_column('connection', 'country')
    op.drop_column('connection', 'dateVisisted')
    # ### end Alembic commands ###
