"""connections table

Revision ID: 576df62261f6
Revises: 76175df5ed3c
Create Date: 2021-07-05 00:04:56.048612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '576df62261f6'
down_revision = '76175df5ed3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_connection_isp', table_name='connection')
    op.drop_column('connection', 'isp')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('connection', sa.Column('isp', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.create_index('ix_connection_isp', 'connection', ['isp'], unique=False)
    # ### end Alembic commands ###
