"""fixed typo

Revision ID: 64009bba62ae
Revises: 191544c4cf40
Create Date: 2021-07-04 19:05:43.789062

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64009bba62ae'
down_revision = '191544c4cf40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('connection', sa.Column('dateVisited', sa.Date(), nullable=True))
    op.drop_index('ix_connection_dateVisisted', table_name='connection')
    op.create_index(op.f('ix_connection_dateVisited'), 'connection', ['dateVisited'], unique=False)
    op.drop_column('connection', 'dateVisisted')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('connection', sa.Column('dateVisisted', sa.DATE(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_connection_dateVisited'), table_name='connection')
    op.create_index('ix_connection_dateVisisted', 'connection', ['dateVisisted'], unique=False)
    op.drop_column('connection', 'dateVisited')
    # ### end Alembic commands ###
