"""connections table

Revision ID: 6bc1ea70dac9
Revises: b1b8098b50fb
Create Date: 2021-06-30 09:27:25.627513

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6bc1ea70dac9'
down_revision = 'b1b8098b50fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('connection',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ipAddress', sa.String(length=20), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_connection_date'), 'connection', ['date'], unique=False)
    op.create_index(op.f('ix_connection_ipAddress'), 'connection', ['ipAddress'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_connection_ipAddress'), table_name='connection')
    op.drop_index(op.f('ix_connection_date'), table_name='connection')
    op.drop_table('connection')
    # ### end Alembic commands ###
