"""empty message

Revision ID: 70494dba2725
Revises: 64009bba62ae
Create Date: 2021-07-04 23:47:05.111482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70494dba2725'
down_revision = '64009bba62ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_connection_proxy', table_name='connection')
    op.drop_column('connection', 'proxy')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('connection', sa.Column('proxy', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.create_index('ix_connection_proxy', 'connection', ['proxy'], unique=False)
    # ### end Alembic commands ###
