"""connections table

Revision ID: 76175df5ed3c
Revises: 70494dba2725
Create Date: 2021-07-04 23:48:10.930762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76175df5ed3c'
down_revision = '70494dba2725'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('connection', sa.Column('proxy', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_connection_proxy'), 'connection', ['proxy'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_connection_proxy'), table_name='connection')
    op.drop_column('connection', 'proxy')
    # ### end Alembic commands ###
