"""users table

Revision ID: aa583fcacfac
Revises: 6bc1ea70dac9
Create Date: 2021-06-30 10:33:08.643449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa583fcacfac'
down_revision = '6bc1ea70dac9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('connection', sa.Column('dateVisited', sa.Date(), nullable=True))
    op.drop_index('ix_connection_date', table_name='connection')
    op.create_index(op.f('ix_connection_dateVisited'), 'connection', ['dateVisited'], unique=False)
    op.drop_column('connection', 'date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('connection', sa.Column('date', sa.DATE(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_connection_dateVisited'), table_name='connection')
    op.create_index('ix_connection_date', 'connection', ['date'], unique=False)
    op.drop_column('connection', 'dateVisited')
    # ### end Alembic commands ###
