"""connection table

Revision ID: e986e5042013
Revises: f5e04f1ed774
Create Date: 2021-07-15 11:39:36.111171

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e986e5042013'
down_revision = 'f5e04f1ed774'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('connection', sa.Column('state', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_connection_state'), 'connection', ['state'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_connection_state'), table_name='connection')
    op.drop_column('connection', 'state')
    # ### end Alembic commands ###
