"""connections table

Revision ID: f5e04f1ed774
Revises: 576df62261f6
Create Date: 2021-07-05 00:43:59.587481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5e04f1ed774'
down_revision = '576df62261f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('connection', sa.Column('isp', sa.String(length=200), nullable=True))
    op.create_index(op.f('ix_connection_isp'), 'connection', ['isp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_connection_isp'), table_name='connection')
    op.drop_column('connection', 'isp')
    # ### end Alembic commands ###
